version: '3'
services:
  nginx:
    image: brogdonco/php-nginx
    volumes:
      - ./web:/var/www/html:ro
      - ./vendor:/var/www/vendor:ro
    ports:
      - "8099:8080"
      - "8098:443"
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}